Support for the new 0.61.0 API
Grover-c13/PokeGOAPI-Java pull request #904
Opened 2017-04-09 16:19 UTC by RebliNk17

Added support for the new 0.61.0 api.

Added a Settings listener.
The settings listener should be add as the other listeners in the api.

Need to update protos.
For some reason that didn't work for me.

2017-04-09 16:19 UTC, RebliNk17 reviewed
ignore that

2017-04-09 16:26 UTC, gegy1000 commented on library/src/main/java/com/pokegoapi/api/settings/Settings.java
> +			int[] splitMinimumVer = new int[currentVer.length];
`minimumVer` should be `splitMinimumVer`. What is currently `spltMinimumVer` should not use the length of `currentVer`, but the length of what is currently `minimumVer`. You should probably also handle the case of `currentVer` and `minimumVer` having different lengths.

2017-04-09 16:26 UTC, gegy1000 commented on library/src/resources/.gitignore
> -protoc.exe
What's this?

2017-04-10 09:45 UTC, jabbink requested changes
Check the style conventions

2017-04-10 09:45 UTC, jabbink commented on library/src/main/java/com/pokegoapi/api/settings/Settings.java
> +		if(!response.getSettings().getMinimumClientVersion().isEmpty()) {
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/settings/Settings.java:131:7: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]

2017-04-10 09:45 UTC, jabbink commented on library/src/main/java/com/pokegoapi/api/listener/SettingsListener.java
> +	 void onNewVersionForced(PokemonGo go, String currentVersion, String forcedVersion);
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/listener/SettingsListener.java:17: Indent must use tab characters [RegexpSinglelineJava]

2017-04-10 09:45 UTC, jabbink commented on library/src/main/java/com/pokegoapi/api/listener/SettingsListener.java
> +	 void onNewVersionForced(PokemonGo go, String currentVersion, String forcedVersion);
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/listener/SettingsListener.java:17: 'method def modifier' have incorrect indentation level 3, expected level should be 2. [Indentation]

2017-04-10 09:45 UTC, jabbink commented on library/src/main/java/com/pokegoapi/api/listener/SettingsListener.java
> +	/**
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/listener/SettingsListener.java:10: Block comment has incorrect indentation level 1, expected is 2, indentation should be the same level as line 17. [CommentsIndentation]

2017-04-11 13:57 UTC, closed without merging